version: '3'
services: 
  db:
    image: mariadb:10.4
    container_name: todoer_db
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=Lin08Uxs
  pma:
    image: phpmyadmin/phpmyadmin:latest
    container_name: todoer_pma
    ports: 
      - "8100:80"
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=Lin08Uxs
      - PMA_PORT=3306
      - PMA_HOST=db
  node:
    build: .
    container_name: todoer_node
    ports: 
      - "8001:8001"
    volumes: 
      - ./:/home/source
    depends_on:
      - db
    command: npm run local
  redis:
    container_name: 'todoer_redis'
    image: redis:latest
    ports:
      - "6379:6379"
